name: Earth-app Push workflow

on:
  push:
    branches: main
    paths: 
    - earth-app/
    - .github/workflows/push.yaml


jobs:
  build:
    runs-on: k8s-runner

    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - run: terraform init -input=false
      - run: terraform apply -input=false -auto-approve