name: Apply terraform

on:
  push:
    branches: master

jobs:
  build:
    runs-on: k8s-runner

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
      - run: terraform init -input=false
      - run: terraform apply -input=false -auto-approve
        env: 
          GITHUB_TOKEN: '${{ secrets.TOKEN }}'
